### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by wboeke** [CCurl/c3#2]
Startup time of c3 is very long: several seconds. The cause is a timing test in tests.f, wich is loaded automatically. Maybe this should be skipped?

Another remark: the file is named c3.cpp, so the compiler thinks it is really a Cpp file. However, actually it is pure C. Maybe rename it?

Besides: I like c3 very much. It packs a lot functionallity in a small file, it is rather robust, and has good error messages.

**Comment by CCurl** [comment]
Wow ... thanks! The tests were put in there to test the speed of the compiled code. They are totally optional and you can definitely remove them.
I put them in there because using Visual Studio on Windows, there is a weird behavior where for some reason the speed slows down depending on something that is not clear, but you can't really determine if it slowed down unless you do a lot of iterations. Linux is generally slower, and more consistent.

FWIW, I have a branch (named 'next') which will fix a few bugs, save some space, and add a little more functionality. It also moves the timing stuff into a new file 'tests.f'. I will be doing a pull-request for that pretty soon.

**Comment by CCurl** [comment]
Re the name, Arduino (v1.x) only recognizes .cpp files, not .c files. I think v2.x doesn't have that problem. I can rename it to .c and see what happens when I get to the point of adding support for building/deploying to development boards.
