### ISSUE TITLE
string.c3 stack

### ISSUE THREAD

**Issue by arblake** [CCurl/c3#20]
Loading string.c3 leaves 4 numbers, addresses i assume, on the stack.

**Comment by arblake** [comment]
Specifically these 2 words
 s-catn   and s-from-sz

**Comment by CCurl** [comment]
Yeah ... you are finding all my loose ends. I had a non "standard" begin/while construct. I changed it to be more like a "standard" Forth with begin/while/repeat. I forgot to update the string.c3 in the main repo to support it. The fix for that will be in my next PR.

FWIW, the corrected/updated version of string.c3 is here for now:

https://github.com/CCurl/c3/blob/version-83/string.c3

**Comment by CCurl** [comment]
i believe that they are now ...

It USED to be:

begin ... (cond) while

Now it is:

begin (flag) while ... repeat

Of course, it COULD be however you decide it to be as the definitions are not baked-in:

: begin  here         ; immediate
: until  (jmpz) c, , ; immediate
: again  (jmp) c, , ; immediate
: while  (jmpz) c, here 0 , ; immediate
: repeat swap (jmp) c, , here swap ! ; immediate
: for 0 swap do ; inline
: next -loop ; inline

**Comment by arblake** [comment]
Thanks
