### ISSUE TITLE
C3 on SOLARIS with SPARC

### ISSUE THREAD

**Issue by arblake** [CCurl/c3#60]
Hi, I have managed to get C3 compiled ...... well it creates an executable. These are  a few initial tests.

 ok
1 2 + .
-[word:.]?- ok
1 DUP
 ok
DROP
 ok

It may not be loading block-001.c3

**Comment by CCurl** [comment]
Have a look at lookforfile() in sys-pc.cpp. you can put a printf in there to see if it finds the file.

**Comment by CCurl** [comment]
Or tryopen()

**Comment by CCurl** [comment]
c3.h ... uncomment out _SYS_LOAD_

**Comment by arblake** [comment]
I now have it reading sys-pc and sys-load as part of complication. I created a processor type SPARC and an operating system type IS_SOLARIS. It does the same as IS_LINUX but gives me more potential flexibility. When I try to run I get this

adrian@Mulach:~/c3$ ./c3
Size of code array: 98304
Storing number: 2 at address: 10011e9a4
Storing number: 3 at address: 10011e9a7
Storing number: 4 at address: 10011e9aa
Storing number: 5 at address: 10011e9ad
Storing number: 6 at address: 10011e9b0
Storing number: 7 at address: 10011e9b3
Storing number: 8 at address: 10011e9b6
Storing number: 10 at address: 10011e9b9
Storing number: 38 at address: 10011e9bc
Storing number: 46 at address: 10011e9bf
Storing number: 12 at address: 10011e9ce
Storing number: 20240517 at address: 10011ea7b
Comma: Storing 20240517 at address 10011ea7c
Error: Misaligned memory access in Store function

**Comment by CCurl** [comment]
So with the x86, mulit-byte values do not have to be aligned in any way. On many develop boards, they have to be aligned to an even address. It looks like the SPARC also needs some sort of alignment. It's curious though, because $10011ea7c is aligned on a 4-byte boundary. It this a 64-bit system? Maybe it needs to be aligned on an 8-bit boundary?

FWIW, I use this for the systems that need to have aligned numbers (32-bit). It stores and fetches them byte-by-byte, which sucks, but it works. If CELLs are 64-bits in this system, it would need 4 more S1's and 4 more G1's. Or the address would need to be aligned however the Solaris needs it up front.

```
#ifdef NEEDS_ALIGN
  #define S1(x, y) (*(x)=((y)&0xFF))
  #define G1(x, y) (*(x)<<y)
  void Store(char *l, cell_t v) { S1(l,v); S1(l+1,v>>8); S1(l+2,v>>16); S1(l+3,v>>24); }
  cell_t Fetch(const char *l) { return (*l)|G1(l+1,8)|G1(l+2,16)|G1(l+3,24); }
#else
  void Store(char *loc, cell_t x) { *(cell_t*)loc = x; }
  cell_t Fetch(const char *loc) { return *(cell_t*)loc; }
#endif
```
