### ISSUE TITLE
Initialization doesn't seem to be working on the Raspberry Pi Pico

### ISSUE THREAD

**Issue by znmeb** [CCurl/c3#64]
I've got the compiles and uploads working, but the part where it loads the dictionary doesn't seem to be working on the Raspberry Pi Pico:

```
Monitoring
Monitor port settings:
  baudrate=115200
  bits=8
  dtr=on
  parity=none
  rts=on
  stop_bits=1

Connecting to /dev/ttyACM0. Press CTRL-C to exit.
Hello.
LittleFS: begin ...done.
LittleFS: initialized-[word:LOAD]?--[word:C3]?-c3 - v2024.5.17 - Chris Curl
1600 code bytes used, 58680 bytes free.
5256 dictionary bytes used, 219 words.
23 variable bytes used, 98281 bytes free. ok
2 3 + .
2 3 + .
```

It's echoing what I type but doesn't seem to be interpreting it. This is what it does on the Linux build:
```
❯ ./c3
c3 - v2024.5.17 - Chris Curl
2189 code bytes used, 89203 bytes free.
6912 dictionary bytes used, 216 words.
35 variable bytes used, 4194269 bytes free.

Block  Description
-----  ------------------
 001   Core c3 words
 002   File handling words
 003   String words
 005   Screen words
 006   Utility words
 044   Accept
 200   Benchmarks
 999   This help ok
2 3 + .
5  ok
```

**Comment by CCurl** [comment]
Re the errors on startup: sorry ... stupid me. The error '[word:LOAD]?' is because I haven't tried running on a Pico in a while (I had changed BLOAD to LOAD on the PC version, but didn't update the INO file). The error '[word:C3]?' is because I haven't tried to use the built-in words for a while (I changed LEXICON to LEX! and didn't update sys-load.cpp). They are updated in this latest build (version 2024.11.10). Hopefully that will fix the errors loading the words. I haven't had time to dig up my Pico to try it out; I'll do that as soon as I can.

Re the "it's not executing": my best guess is that it's looking for a 13 (c3.ino, line 105) to trigger the execute, and maybe the monitor program is conigured to send a 10, not a 13?

**Comment by znmeb** [comment]
> Re the "it's not executing": my best guess is that it's looking for a 13 (c3.ino, line 105) to trigger the execute, and maybe the terminal program you are is configured to send a 10, not a 13?

It's configurable in the Arduino IDE - you can send either LF, CR or CR/LF. IIRC the Linux standard is that "Enter" sends CR and the computer echoes the CR and then responds with an LF. I'll check them both out with the new code.

**Comment by znmeb** [comment]
OK ... it's working now both in the IDE and from the command line! And it is "CR" - I checked it in the IDE.

**Comment by znmeb** [comment]
I keep forgetting to ask you this - would you be interested in talking about c3 and c4 at the Silicon Valley Forth Interest Group's annual Forth Day next Saturday? 

https://www.meetup.com/sv-fig/events/303997241/

I'll probably be talking briefly about what I'm doing with c3, but I think the people there will be extremely interested in c4. There's been quite a lot of interest in colorForth recently.

**Comment by CCurl** [comment]
Wow ... I never have time for those things ... the wife has me on a pretty short leash on the weekends. Plus, I wouldn't even know what to say. I can, however, see what I can do to beef up the documentation on C4 in case you happen to mention it at the meeting :). Please feel free to mention it if you want.

The other thing I have been thinking about more lately ... it feels like C4 would be a good candidate for dev boards, since the codes are all 32-bit, so the alignment issue is essentially gone for that. It would be easy enough to write a word to align an address to that fetches could be full-speed (I will do that for C3 as well). 

I think I'm at the point with C4 that I can start looking at taking a copy of it and "Arduinoify-ing" it. It should be pretty straight-forward.

**Comment by znmeb** [comment]
> Wow ... I never have time for those things ... the wife has me on a pretty short leash on the weekends. Plus, I wouldn't even know what to say. I can, however, see what I can do to beef up the documentation on C4 in case you happen to mention it at the meeting :). Please feel free to mention it if you want.

OK ... if you want to see some past meetups for inspiration, here's the YouTube channel: https://www.youtube.com/@siliconvalleyforthinterest1736

> 
> The other thing I have been thinking about more lately ... it feels like C4 would be a good candidate for dev boards, since the codes are all 32-bit, so the alignment issue is essentially gone for that. It would be easy enough to write a word to align an address to that fetches could be full-speed (I will do that for C3 as well).
> 
> I think I'm at the point with C4 that I can start looking at taking a copy of it and "Arduinoify-ing" it. It should be pretty straight-forward.

That sounds great! I'd think it would be faster than C3, but probably also take up more flash space. Incidentally, the only operations I would add to either C3 or C4 are halfword signed and unsigned fetches and stores. I was working on an assembly language Forth for the RP2040 and I was able to do a lot with things like a 16x16 `*/MOD`.
